name: Release

on:
  workflow_dispatch:
  push:
    tags:
      - "v*"

jobs:
  publish:
    runs-on: ubuntu-latest
    environment: release # Optional: for enhanced security
    permissions:
      id-token: write # Required for OIDC token exchange
    steps:
      - uses: actions/checkout@v4
      - uses: rust-lang/crates-io-auth-action@v1
        if: github.ref_type == 'tag'
        id: auth
      - uses: katyo/publish-crates@v2
        with:
          registry-token: ${{ steps.auth.outputs.token }}
          dry-run: ${{ github.ref_type != 'tag' }}
          ignore-unpublished-changes: true
