name: Release

on:
  workflow_dispatch:
  push:
    tags:
      - "v*"

jobs:
  publish:
    runs-on: ubuntu-latest
    environment: release # Optional: for enhanced security
    permissions:
      id-token: write # Required for OIDC token exchange
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
        with:
          targets: thumbv7m-none-eabi
      - name: Dry run
        if: github.ref_type != 'tag'
        run: cargo publish --features=stm32f103,xG --dry-run
      - uses: rust-lang/crates-io-auth-action@v1
        if: github.ref_type == 'tag'
        id: auth
      - name: Publish crate
        if: github.ref_type == 'tag'
        run: cargo publish --features=stm32f103,xG
        env:
          CARGO_REGISTRY_TOKEN: ${{ steps.auth.outputs.token }}
