[package]
    authors = ["Jalon Wong <jalonwong@gmail.com>"]
    edition = "2024"
    license = "MIT OR Apache-2.0"
    name = "f103c8"
    version = "0.1.0"

[dependencies]
    [dependencies.stm32f1-hal]
        features = ["stm32f103", "x8", "critical-section-single-core"]
        path = "../.."

[profile.release]
    codegen-units = 1
    debug = true
    lto = true
    opt-level = 0
